articles/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/1', permanent=False)),
    url(r'^(?P<page>\d+)/$', views.index, name="index"),
    #url(r'^$', views.index, name="index"),
    url(r'^category/(?P<pk>\d+)/(?P<slug>.+)/$', views.CategoryView, name="category"),
    url(r'^post/(?P<pk>\d+)/(?P<slug>.+)/$', views.PostView, name="post"),
    url(r'^search/$', views.searchView, name="search"),
    url(r'^database_entry/$', views.database_entry),

]

feverpitch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("articles.urls", namespace="articles")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^newsletter/', include('newsletter.urls', namespace="newsletter")),
    url(r'^football-center/', include("stats.urls", namespace="stats")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/roster/$', views.teamRoster, name="team-roster"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/schedule/$', views.teamSchedule, name="team-schedule"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/result/$', views.teamResult, name="team-result"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/$', views.teamPage, name="team-page"),
    url(r'^cups-and-leagues/(?P<league_id>\d+)/(?P<league_slug>.+)/$', views.leaguePage, name="leaguePage"),
    # url(r'^cups-and-leagues/(?P<cup_id>\d+)/(?P<cup_name>.+)/$', views.cupPage, name="cup-page"),
    url(r'^cups-and-leagues/$', views.clIndex, name="cups-and-leagues"),
    url(r'^players/$', views.playerIndex, name="players"),
    url(r'^players/(?P<player_id>\d+)/(?P<player_slug>.+)/$', views.playerPage, name="player-page"),
    url(r'^match/(?P<match_id>\d+)/(?P<match_slug>.+)/$', views.matchPage, name="match"),
]

articles/models.py
from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils import timezone

now = timezone.now()

class Category(models.Model):
    date_added = models.DateField(default=now)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Article(models.Model):
    date_added = models.DateField(default=now)
    category = models.ForeignKey(Category)
    published = models.BooleanField(default=True, choices=(
        (True, "Yes"),
        (False, "No")
    ))
    featured = models.BooleanField(default=True, choices=(
        (True, "Yes"),
        (False, "No")
    ))
    title = models.CharField(max_length=150)
    author = models.ForeignKey(User)
    introImage = models.FileField(upload_to="articles/intro-images", max_length=150)
    introText = models.TextField()
    mainImage = models.FileField(upload_to="articles/main-images", max_length=150, blank=True, null=True)
    content = RichTextField(blank=True, null=True)
    keywords = models.CharField(max_length=250, blank=True, null=True)
    descriptionMeta = models.TextField(blank=True, null=True)
    hits = models.IntegerField(default=0)

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render

from .models import Article, Category
from stats.models import Team, Competition
import json
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_protect



description = "Fever Pitch is Indias only online Indian Football News and Magazine Website. From Mohan Bagar to Meghalaya FC, we cover all!"
keywords = "feverpitch, fever pitch, fever pitch india, mohan bagan, football india, football in india, indian football team, india fc, football clubs in india"
categories = Category.objects.all()
teams = Team.objects.all().order_by("-date_added")
competitions = Competition.objects.all()


def index(request, page):
    page=int(page)
    print("page=", page)
    page_range= range(page-2, page+3)

    homepage_posts = Article.objects.filter(published=True, featured=True).order_by("-date_added")[:2]
    home_bottom4 = Article.objects.filter(published=True, featured=True).order_by("-date_added")[3:6]
    latest_articles = Article.objects.filter(published=True).order_by("-date_added")[:5]
    #more_articles = Article.objects.filter(published=True).order_by("-date_added")
    popular_news = Article.objects.filter(published=True).order_by("hits")[:10]
    #///////////////////////////////////////////


    more_articles_list = Article.objects.filter(published=True).order_by("-date_added")
    print("page=", page)

    paginator = Paginator(more_articles_list, 4)

    try:
        more_articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        more_articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        more_articles = paginator.page(paginator.num_pages)

    #///////////////////////////////////////////


    return render(request, "index.html", {
    "homepagePosts":homepage_posts, "homeb4":home_bottom4, "latest_articles":latest_articles,
    "description":description, "keywords":keywords, "articles":more_articles, "popular":popular_news,
    "page_range":page_range,"total_pages": paginator.num_pages,

    })


def CategoryView(request, pk, slug):
    category = Category.objects.get(pk=pk)
    posts = Article.objects.filter(published=True).order_by("-date_added")

    return render(request, "articles/category.html", {
    "description":description, "keywords": keywords, "posts":posts,
    "category":category,
    })

def PostView(request, pk, slug):
    post = Article.objects.get(pk=pk)
    post.hits = post.hits+1
    post.save()

    if not post.descriptionMeta:
        if not post.introText:
            description = "Fever Pitch is India's only online Indian Football News and Magazine Website. From Mohan Bagar to Meghalaya FC, we cover all!"
        else:
            description = post.introText
    else:
        description = post.descriptionMeta

    if not post.keywords:
        keywords = "feverpitch, fever pitch, fever pitch india, mohan bagan, football india, football in india, indian football team, india fc, football clubs in india"
    else:
        keywords = post.keywords

    return render(request, "articles/post.html", {
    "post":post, "description":description, "keywords":keywords,
    })


def searchView(request):
    page = request.GET.get("page")
    page=int(page)
    print("page=", page)
    page_range= range(page-2, page+3)

    term = request.GET.get("term")
    results_list = Article.objects.filter(title__icontains=term)

    paginator = Paginator(results_list, 5)

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)

    return render(request, "search.html", {
    "results":results,
    "term": term,
    "page_range":page_range,"total_pages": paginator.num_pages,
    "count": len(results_list),
    })

def database_entry(request):
    with open('file_final.json') as data_file:
        data = json.load(data_file)
        print (data)
        for each in data:
        	# print each["id"],each["date_added"], each["author"] , each["intro_text"], each["content"], each["image"], each["category"]
            article = Article(
                date_added = each["date_added"],
                category = Category.objects.get(pk=1), #each["category"], iske setting karni padegi ForeignKey hai ye
                title = each["title"],
                author = User.objects.get(pk=1),  #each["author"], , iske setting karni padegi ForeignKey hai ye
                mainImage = each["image"],
                introText = each["intro_text"],
                introImage = each["image"],
                content = each["content"],
                )
            article.save()




    return JsonResponse({'result':"Entries done to database, check ur admin-article page to see the difference"})

templates/articles/category.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{category.name}}
{% endblock title %}

{% block content %}

    <!-- Page Heading
    ================================================== -->
    <div class="page-heading">
      <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <h1 class="page-heading__title">{{category.name}}</h1>
            <ol class="page-heading__breadcrumb breadcrumb">
              <li><a href="{% url "articles:index" %}">Home</a></li>
              <li class="active">{{category.name}}</li>
            </ol>
          </div>
        </div>
      </div>
    </div>


    <!-- Content
    ================================================== -->
    <div class="site-content">
      <div class="container">

        <div class="row">
          <!-- Content -->
          <div class="content col-md-8">

            <!-- Posts Grid -->
            <div class="posts posts--cards post-grid post-grid--2cols post-grid--fitRows row">
              {% for each in posts %}
                <div class="post-grid__item col-xs-6">
                  <div class="posts__item posts__item--card posts__item--category-1 card">
                    <figure class="posts__thumb">
                      <div class="posts__cat">
                        <span class="label posts__cat-label">{{each.category.name}}</span>
                      </div>
                      <a href="{% url "articles:post" each.pk each.title|slugify %}"><img src="{{each.introImage.url}}" alt=""></a>
                    </figure>
                    <div class="posts__inner card__content">
                      <a href="#" class="posts__cta"></a>
                      <time datetime="2017-08-23" class="posts__date">{{each.date_added}}</time>
                      <h6 class="posts__title"><a href="{% url "articles:post" each.pk each.title|slugify %}">{{each.title}}</a></h6>
                      <div class="posts__excerpt">
                        {{each.introText}}
                      </div>
                    </div>                    
                  </div>
                </div>
              {% endfor %}
            </div>
            <!-- Post Grid / End -->

            <!-- Post Pagination -->
            <nav class="post-pagination text-center">
              <ul class="pagination pagination--lg">
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><span>...</span></li>
                <li><a href="#">16</a></li>
              </ul>
            </nav>
            <!-- Post Pagination / End -->


          </div>
          <!-- Content / End -->

          <!-- Sidebar -->
          {% include "sidebar.html" %}
          <!-- Sidebar / End -->
        </div>

      </div>
    </div>

    <!-- Content / End -->

{% endblock content %}

templates/articles/post.html
{% extends "base.html" %}
{% load staticfiles %}
{% load disqus_tags %}

{% block title %}
{{post.title}} {{post.category.name}}
{% endblock title %}

{% block content %}

    <!-- Page Heading
    ==================================================
      {% comment %} url("../images/football/page-heading.jpg");
      style="background-image:'{{post.mainImage}}' {% endcomment %}
    -->
    
    <div class="page-heading page-heading--overlay" style="background-image:url('{{post.mainImage.url}}')" >
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <!-- Post Meta - Top -->
            <div class="post__meta-block post__meta-block--top posts__item--category-2">

              <!-- Post Category -->
              <div class="post__category">
                <span class="label posts__cat-label">{{post.category.name}}</span>
              </div>
              <!-- Post Category / End -->

              <!-- Post Title -->
              <h1 class="page-heading__title">{{post.title}}</h1>
              <!-- Post Title / End -->

              <div class="posts__date"><time datetime="2017-08-23">{{post.date_added}}</time></div>

              <!-- Post Meta Info -->
              <ul class="post__meta meta">
                <li class="meta__item meta__item--author">
                  <!-- Post Author -->
                  <div class="post-author">
                    <div class="post-author__info">
                      <h4 class="post-author__name">{{post.author.first_name}} {{post.author.last_name}}</h4>
                    </div>
                  </div>
                  <!-- Post Author / End -->
                </li>
                <li class="meta__item meta__item--views">{{post.hits}}</li>
              </ul>
              <!-- Post Meta Info / End -->

            </div>
            <!-- Post Meta - Top / End -->
          </div>
        </div>
      </div>
    </div>

    <!-- Content
    ================================================== -->
    <div class="site-content">
      <div class="container">

        <div class="row">
          <!-- Content -->
          <div class="content col-md-8 col-md-offset-2">

            <!-- Article -->
            <article class="card post post--single post--extra-top">
              <div class="card__content">

                <div class="post__content">
                  {{post.content|safe}}
                </div>
                <footer class="post__footer">
                  <div class="post__tags">
                    <a href="#" class="btn btn-default btn-outline btn-xs">Results</a>
                    <a href="#" class="btn btn-default btn-outline btn-xs">Incorporation</a>
                    <a href="#" class="btn btn-default btn-outline btn-xs">Finals</a>
                    <a href="#" class="btn btn-default btn-outline btn-xs">Uniforms</a>
                  </div>
                </footer>

              </div>
            </article>
            <!-- Article / End -->

            <!-- Post Sharing Buttons -->
            <div class="addthis_inline_share_toolbox"></div>
            <!-- Post Sharing Buttons / End -->


            <!-- Related Posts -->
            <div class="post-related post-related--condensed row">
              <div class="col-xs-6">
                <!-- Prev Post -->
                <div class="card post-related__prev">
                  <div class="card__content">

                    <!-- Prev Post Links -->
                    <a href="#" class="btn-nav btn-nav--condensed">
                      <i class="fa fa-angle-left"></i>
                    </a>
                    <!-- Prev Post Links / End -->

                    <ul class="posts posts--simple-list">
                      <li class="posts__item posts__item--category-1">
                        <div class="posts__inner">
                          <div class="posts__cat">
                            <span class="label posts__cat-label">Injuries</span>
                          </div>
                          <h6 class="posts__title"><a href="#">The team is gonna make a trip to the beach for a small vacation</a></h6>
                          <time datetime="2017-08-23" class="posts__date">August 23rd, 2017</time>
                        </div>
                      </li>
                    </ul>

                  </div>
                </div>
                <!-- Prev Post / End -->
              </div>
              <div class="col-xs-6">
                <div class="card post-related__next">
                  <!-- Next Post -->
                  <div class="card__content">

                    <ul class="posts posts--simple-list">
                      <li class="posts__item posts__item--category-3">
                        <div class="posts__inner">
                          <div class="posts__cat">
                            <span class="label posts__cat-label">The League</span>
                          </div>
                          <h6 class="posts__title"><a href="#">Veteran player Xavier McCoy will coach The Sharks next league</a></h6>
                          <time datetime="2017-08-23" class="posts__date">August 23rd, 2017</time>
                        </div>
                      </li>
                    </ul>

                    <!-- Next Post Link -->
                    <a href="#" class="btn-nav btn-nav--condensed">
                      <i class="fa fa-angle-right"></i>
                    </a>
                    <!-- Next Post Link / End -->

                  </div>
                  <!-- Next Post / End -->
                </div>
              </div>
            </div>
            <!-- Related Posts / End -->


            <!-- Post Comments -->
            <div class="post-comments card">
              {% disqus_show_comments %}
            </div>
            <!-- Post Comments / End -->


            <!-- Post Comment Form -->
            <div class="post-comment-form card">
              <header class="post-comment-form__header card__header">
                <h4>Write a Comment</h4>
              </header>
              <div class="post-comment-form__content card__content">
                <form action="#" class="comment-form">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="control-label" for="input-name">Your Name <span class="required">*</span></label>
                        <input type="text" id="input-name" name="input-name" class="form-control">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="control-label" for="input-email">Your Email <span class="required">*</span></label>
                        <input type="email" id="input-email" name="input-email" class="form-control">
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label" for="textarea-comment">Your Comment <span class="required">*</span></label>
                    <textarea name="textarea-comment" id="textarea-comment" rows="7" class="form-control"></textarea>
                  </div>
                  <div class="form-group mb-0">
                    <button type="submit" class="btn btn-primary-inverse btn-block btn-lg">Post Your Comment</button>
                  </div>
                </form>
              </div>
            </div>
            <!-- Post Comment Form / End -->


          </div>
          <!-- Content / End -->

        </div>

      </div>
    </div>

    <!-- Content / End -->

{% endblock content %}