feverpitch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("articles.urls", namespace="articles")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^newsletter/', include('newsletter.urls', namespace="newsletter")),
    url(r'^football-center/', include("stats.urls", namespace="stats")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/roster/$', views.teamRoster, name="team-roster"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/schedule/$', views.teamSchedule, name="team-schedule"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/result/$', views.teamResult, name="team-result"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/$', views.teamPage, name="team-page"),
    url(r'^cups-and-leagues/(?P<league_id>\d+)/(?P<league_slug>.+)/$', views.leaguePage, name="leaguePage"),
    # url(r'^cups-and-leagues/(?P<cup_id>\d+)/(?P<cup_name>.+)/$', views.cupPage, name="cup-page"),
    url(r'^cups-and-leagues/$', views.clIndex, name="cups-and-leagues"),
    url(r'^players/$', views.playerIndex, name="players"),
    url(r'^players/(?P<player_id>\d+)/(?P<player_slug>.+)/$', views.playerPage, name="player-page"),
    url(r'^match/(?P<match_id>\d+)/(?P<match_slug>.+)/$', views.matchPage, name="match"),
]

stats/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor_uploader.fields import RichTextUploadingField

from django.db.models import signals
from django.dispatch import receiver

FORMAT_CHOICES = (
    (1, "League"),
    (2, "League + Knockout"),
    (3, "Group-Wise League + Knockout"),
    (4, "Group-Wise League + Leauge"),
    (5, "Group Wise League + Group Wise League + Knockouts"),
    (6, "League + Group-wise Leauge"),
    (7, "Group-wise League + League + Knockout"),
)
PLAYER_TYPES = (
    (1, "Centre-back"),
    (2, "Sweeper"),
    (3, "Full-back"),
    (4, "Wing-back"),
    (5, "Centre midfield"),
    (6, "Defensive midfield"),
    (7, "Attacking midfield"),
    (8, "Wide midfield"),
    (9, "Centre forward"),
    (10, "Second striker"),
    (11, "Winger"),
    (12, "Goalkeeper"),
    (13, "Defensive"),
    (14, "Midfield"),
    (15, "Attacking"),
)

MANAGER_TYPES = (
    (1, "Technical Director"),
    (2, "Head Coach"),
    (3, "Asst. Coach"),
    (4, "GK Coach"),
    (5, "Manager"),
)

class Competition(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    league_format = models.IntegerField(choices=FORMAT_CHOICES, default=0)
    logo = models.FileField(upload_to="competitions/logos/", max_length=150)

    def __str__(self):
        return self.name

class Season(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=50)
    competiton = models.ForeignKey(Competition)

    def __str__(self):
        return self.name

class Venue(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    address = models.TextField(blank=True, null=True)
    city = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        return self.name

class Player(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="players", blank=True, null=True)
    dob = models.DateField(blank=True, null=True, help_text="Date of Birth")
    nationality = models.CharField(max_length=50, default="Indian")
    height = models.IntegerField(default=100)
    weight = models.FloatField(default=100)
    player_type = models.IntegerField(choices=PLAYER_TYPES, default=0)
    about= models.CharField(max_length=500, null=True)
    def __str__(self):
        return self.name

class Management(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="management", blank=True, null=True)
    dob = models.DateField(blank=True, null=True, help_text="Date of Birth")
    nationality = models.CharField(max_length=50, default="Indian")
    height = models.IntegerField(default=100)
    weight = models.FloatField(default=100)
    manager_type = models.IntegerField(choices=MANAGER_TYPES, default=0)

    def __str__(self):
        return self.name

class Team(models.Model):
    date_added = models.DateField(default=timezone.now)
    competition = models.ForeignKey(Competition, blank=True, null=True, related_name='competition_admin')
    name = models.CharField(max_length=50)
    logo = models.FileField(upload_to="teams/logos", blank=True, null=True, max_length=150)
    state = models.CharField(max_length=35)
    players=models.ManyToManyField(Player)
    managers=models.ManyToManyField(Management)
    locations=models.CharField(max_length=35, null=True)
    about= models.CharField(max_length=500, null=True)
    email=models.EmailField(null=True)
    contact_no = PhoneNumberField(null=True)

    def __str__(self):
        return self.name


class Match(models.Model):
    date_added = models.DateField(default=timezone.now)
    date_of_match = models.DateField()
    season = models.ForeignKey(Season, default=None)
    preview = RichTextUploadingField(blank=True, null=True)
    report = RichTextUploadingField(blank=True, null=True)
    home_team = models.ForeignKey(Team, related_name="home")
    home_players_playing = models.ManyToManyField(Player, blank=True, related_name="home_players")
    home_players_substitutes = models.ManyToManyField(Player, blank=True, related_name="home_players_subs")
    away_team = models.ForeignKey(Team, related_name="away")
    away_players_playing = models.ManyToManyField(Player, blank=True, related_name="away_players")
    away_players_substitutes = models.ManyToManyField(Player, blank=True, related_name="away_players_subs")
    home_score = models.IntegerField(default=-1)
    away_score = models.IntegerField(default=-1)
    match_location = models.ForeignKey(Venue)
    published = models.BooleanField(default=False, choices=(
        (True, "Yes"),
        (False, "No"),
    ))
    def __init__(self, *args, **kwargs):
        print("init called")
        super(Match, self).__init__(*args, **kwargs)
        self.__important_fields = ['home_score', 'away_score',]
        for field in self.__important_fields:
            setattr(self, '__original_%s' % field, getattr(self, field))

    def has_changed(self):
        orig = '__original_%s' % self.__important_fields[0]
        home=getattr(self, orig)
        orig = '__original_%s' % self.__important_fields[1]
        away=getattr(self, orig)

        for field in self.__important_fields:
            orig = '__original_%s' % field
            if getattr(self, orig) != getattr(self, field):
                return True, home, away
        return False,  home, away

    def __str__(self):
        #return "Match between " + self.home_team.name + " and " + self.away_team.name + " on " + str(self.date_of_match) + " at " + self.match_location
        return "Match between " + self.home_team.name + " and " + self.away_team.name
    def match_description(self):
        #return "Match between " + self.home_team.name + " and " + self.away_team.name + " on " + str(self.date_of_match) + " at " + self.match_location
        return "Match between " + self.home_team.name + " and " + self.away_team.name

    def getHome(self):
        return self.home_team.name

    def getAway(self):
        return self.away_team.name

@receiver(signals.post_save, sender=Match)
def match_finish(sender, instance, created, **kwargs):

    if instance.home_score > -1 and instance.away_score > -1 :
        print ("match finished")
        #print("instance", instance.season, instance.season.id)
        oldHomeScore=0
        oldAwayScore=0
        changed,oldHomeScore, oldAwayScore = instance.has_changed()
        if changed:
            print ("instance has changed after save")
            hPoints=-1
            aPoints=- 1
            hWin=-1
            aWin=-1
            draw=-1

            if instance.home_score > instance.away_score:
                if(oldHomeScore ==-1 and oldAwayScore ==-1):
                    print("for first time -1 -1")
                    hPoints=3
                    aPoints=0
                    hWin=1
                    aWin=0
                    draw=0
                elif(oldHomeScore > oldAwayScore):
                    hPoints=0
                    aPoints=0
                    hWin=0
                    aWin=0
                    draw=0
                elif(oldHomeScore < oldAwayScore):
                    hPoints=3
                    aPoints=-3
                    hWin=1
                    aWin=-1
                    draw=0
                elif(oldHomeScore == oldAwayScore):
                    hPoints=1
                    aPoints=-2
                    hWin=1
                    aWin=0
                    draw=-1


            elif instance.home_score < instance.away_score:

                if(oldHomeScore ==-1 and oldAwayScore ==-1):
                    print("for first time -1 -1")
                    hPoints=0
                    aPoints=3
                    hWin=0
                    aWin=1
                    draw=0
                elif(oldHomeScore > oldAwayScore):
                    hPoints=-3
                    aPoints=3
                    hWin=-1
                    aWin=1
                    draw=0
                elif(oldHomeScore < oldAwayScore):
                    hPoints=0
                    aPoints=0
                    hWin=0
                    aWin=0
                    draw=0
                elif(oldHomeScore == oldAwayScore):
                    hPoints=-2
                    aPoints=1
                    hWin=0
                    aWin=1
                    draw=-1

            else:
                if(oldHomeScore ==-1 and oldAwayScore ==-1):
                    print("for first time -1 -1")
                    hPoints=2
                    aPoints=2
                    hWin=0
                    aWin=0
                    draw=1
                elif(oldHomeScore > oldAwayScore):
                    hPoints=-3+2
                    aPoints=2
                    hWin=-1
                    aWin=0
                    draw=1
                elif(oldHomeScore < oldAwayScore):
                    hPoints=2
                    aPoints=-3+2
                    hWin=0
                    aWin=-1
                    draw=1
                elif(oldHomeScore == oldAwayScore):
                    hPoints=0
                    aPoints=0
                    hWin=0
                    aWin=0
                    draw=0

            season = Season.objects.get(pk=instance.season.id)
            competition = Competition.objects.get(pk = season.competiton.id)
            try:
                pointTable = PointTable.objects.get(competition=competition)
            except:
                pointTable = None

            if pointTable:
                print("pointTable already exists, check if teamPoints exists")

stats/views.py
from django.shortcuts import render
from datetime import datetime, timedelta
from .models import Team, Match, Competition, Player, Season, PointTable, TeamPoint
teams = Team.objects.all().order_by("-date_added")

def index(request):
    return render(request, "index.html", {
    })

def clIndex(request):
    return render(request, "index.html", {
    })

def cupPage(request, cup_id, cup_name):
    return render(request, "index.html", {
    })

def playerPage(request, player_id, player_slug):
    player_id = int(player_id)
    player = Player.objects.get(pk=player_id)
    #print ("player=", player);
    return render(request, "stats/player.html", {
        "player":player,
    })

def playerIndex(request):
    return render(request, "players.html", {
    })

def matchPage(request, match_id, match_slug):
    match=Match.objects.get(pk=match_id);
    #for each in match.home_players_playing.all():
    #    print each.picture.url
    return render(request, "stats/match.html", {
        'match': match,
    })

def teamIndex(request):
    competitions = Competition.objects.all()
    teams = Team.objects.all()
    return render(request, "stats/teams.html", {
    })


def teamPage(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)
    matches=Match.objects.filter(home_team=team_id)



    return render(request, "stats/team.html", {
        "team":team,

    })


def teamRoster(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)

    return render(request, "stats/team-roster.html", {
        "team":team,
    })

def teamSchedule(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)
    matches=Match.objects.all()
    startdate = datetime.today()

    try:
        home_matches = Match.objects.filter(home_team=team_id).filter(date_of_match__gte=startdate)
    except:
        home_matches=None
    try:
        away_matches = Match.objects.filter(away_team=team_id).filter(date_of_match__gte=startdate)
    except:
        away_matches=None


    print("home_matches:", home_matches, "away_matches:", away_matches)

    return render(request, "stats/team-schedule.html", {
    "team":team, "away_matches":away_matches, "home_matches":home_matches,
    })

def teamResult(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)
    matches=Match.objects.all()
    startdate = datetime.today()

    #print("home_matches:", home_matches, "away_matches:", away_matches)

    try:
        home_matches = Match.objects.filter(home_team=team_id).filter(date_of_match__lt=startdate)
    except:
        home_matches=None
    try:
        away_matches = Match.objects.filter(away_team=team_id).filter(date_of_match__lt=startdate)
    except:
        away_matches=None

    #print("home_matches:", home_matches, "away_matches:", away_matches)

    return render(request, "stats/team-result.html", {
    "team":team, "away_matches":away_matches, "home_matches":home_matches,
    })

def leaguePage(request, league_id, league_slug):

    league_id = int(league_id)
    league = Competition.objects.get(pk=league_id)
    seasons = Season.objects.filter(competiton=league)
    #print "season", seasons

    startdate = datetime.today()

    results=Match.objects.filter(season__in=seasons).filter(date_of_match__lt=startdate)
    fixtures=Match.objects.filter(season__in=seasons).filter(date_of_match__gte=startdate).order_by("-date_of_match")
    #print "results", results, "fixtures", fixtures

    teams = Team.objects.filter(competition=league_id);

    pointTable = PointTable.objects.filter(competition=league_id)
    teamPoint = TeamPoint.objects.filter(competition__in=pointTable)

    return render(request, "stats/league.html", {
        "league":league,
        "results":results,
        "fixtures":fixtures,
        # "teams": teams,
        "teamPoint": teamPoint

    })

templates/stats/team-result.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{team.name}} Result
{% endblock title %}

{% block content %}

  <!-- Page Heading
  ================================================== -->
  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
        <h1 class="page-heading__title">{{team.name}} <span class="highlight">Schedule</span></h1>
          <ol class="page-heading__breadcrumb breadcrumb">
            <li><a href="{% url "articles:index" 1 %}">Home</a></li>
            <li><a href="{% url "stats:team-page" team.pk team.name|slugify %}">{{team.name}}</a></li>
            <li class="active">Result</li>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <!-- Team Pages Filter -->
  <nav class="content-filter">
    <div class="container">
      <a href="#" class="content-filter__toggle"></a>
      <ul class="content-filter__list">
        <li class="content-filter__item "><a href="{% url "stats:team-page" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Overview</a></li>
        <li class="content-filter__item "><a href="{% url "stats:team-roster" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Roster</a></li>
        <li class="content-filter__item "><a href="_football_team-standings.html" class="content-filter__link"><small>The Team</small>Standings</a></li>
        <li class="content-filter__item content-filter__item--active"><a href="{% url "stats:team-result" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Latest Results</a></li>
        <li class="content-filter__item "><a href="{% url "stats:team-schedule" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Schedule</a></li></ul>
    </div>
  </nav>



    <div class="site-content">
      <div class="container">

        <div class="card card--has-table">
          <div class="card__header">
            <h4>Results</h4>
          </div>
          <div class="card__content">
            <div class="table-responsive">
              <table class="table table-hover team-schedule team-schedule--full">
                <thead>
                  <tr>
                    <th class="team-schedule__date">Date</th>
                    <th class="team-schedule__versus">Versus</th>
                    <th class="team-schedule__status">Status</th>
                    <th class="team-schedule__compet">Competition</th>
                    <th class="team-schedule__venue">Venue</th>
                  </tr>
                </thead>
                <tbody>
                  {% for each in home_matches %}
                  <tr>
                    <td class="team-schedule__date">{{each.date_of_match}}</td>
                    <td class="team-schedule__versus">
                      <div class="team-meta">
                        <figure class="team-meta__logo">

                          <img src="{{each.away_team.logo.url}}" alt="image">
                        </figure>
                        <div class="team-meta__info">
                          <h6 class="team-meta__name">{{each.away_team}}</h6>
                        </div>
                      </div>
                    </td>
                    <td class="team-schedule__status">Home</td>
                    <td class="team-schedule__compet">{{each.season.competiton}}</td>
                    <td class="team-schedule__venue">{{each.match_location}}</td>
                  </tr>
                  {% endfor %}

                  {% for each in away_matches %}
                  <tr>
                    <td class="team-schedule__date">{{each.date_of_match}}</td>
                    <td class="team-schedule__versus">
                      <div class="team-meta">
                        <figure class="team-meta__logo">

                          <img src="{{each.home_team.logo.url}}" alt="image">
                        </figure>
                        <div class="team-meta__info">
                          <h6 class="team-meta__name">{{each.home_team}}</h6>
                        </div>
                      </div>
                    </td>
                    <td class="team-schedule__status">Away</td>
                    <td class="team-schedule__compet">{{each.season.competiton}}</td>
                    <td class="team-schedule__venue">{{each.match_location}}</td>
                  </tr>
                  {% endfor %}



                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div>
    {% endblock content %}

templates/stats/team-schedule.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{team.name}} Schedule
{% endblock title %}

{% block content %}

  <!-- Page Heading
  ================================================== -->
  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
        <h1 class="page-heading__title">{{team.name}} <span class="highlight">Schedule</span></h1>
          <ol class="page-heading__breadcrumb breadcrumb">
            <li><a href="{% url "articles:index" 1 %}">Home</a></li>
            <li><a href="{% url "stats:team-page" team.pk team.name|slugify %}">{{team.name}}</a></li>
            <li class="active">Schedule</li>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <!-- Team Pages Filter -->
  <nav class="content-filter">
    <div class="container">
      <a href="#" class="content-filter__toggle"></a>
      <ul class="content-filter__list">
        <li class="content-filter__item "><a href="{% url "stats:team-page" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Overview</a></li>
        <li class="content-filter__item "><a href="{% url "stats:team-roster" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Roster</a></li>
        <li class="content-filter__item "><a href="_football_team-standings.html" class="content-filter__link"><small>The Team</small>Standings</a></li>
        <li class="content-filter__item "><a href="{% url "stats:team-result" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Latest Results</a></li>
        <li class="content-filter__item content-filter__item--active"><a href="{% url "stats:team-schedule" team.pk team.name|slugify %}" class="content-filter__link"><small>The Team</small>Schedule</a></li>
      </ul>
    </div>
  </nav>
  <!-- Team Pages Filter / End -->



    <!-- Content
    ================================================== -->
    <div class="site-content">
      <div class="container">

        <!-- Schedule & Tickets -->
        <div class="card card--has-table">
          <div class="card__header">
            <h4>Schedule</h4>
          </div>
          <div class="card__content">
            <div class="table-responsive">
              <table class="table table-hover team-schedule team-schedule--full">
                <thead>
                  <tr>
                    <th class="team-schedule__date">Date</th>
                    <th class="team-schedule__versus">Versus</th>
                    <th class="team-schedule__status">Status</th>
                    <th class="team-schedule__compet">Competition</th>
                    <th class="team-schedule__venue">Venue</th>
                  </tr>
                </thead>
                <tbody>
                  {% for each in home_matches %}
                  <tr>
                    <td class="team-schedule__date">{{each.date_of_match}}</td>
                    <td class="team-schedule__versus">
                      <div class="team-meta">
                        <figure class="team-meta__logo">

                          <img src="{{each.away_team.logo.url}}" alt="image">
                        </figure>
                        <div class="team-meta__info">
                          <h6 class="team-meta__name">{{each.away_team}}</h6>
                        </div>
                      </div>
                    </td>
                    <td class="team-schedule__status">Home</td>
                    <td class="team-schedule__compet">{{each.season.competiton}}</td>
                    <td class="team-schedule__venue">{{each.match_location}}</td>
                  </tr>
                  {% endfor %}

                  {% for each in away_matches %}
                  <tr>
                    <td class="team-schedule__date">{{each.date_of_match}}</td>
                    <td class="team-schedule__versus">
                      <div class="team-meta">
                        <figure class="team-meta__logo">

                          <img src="{{each.home_team.logo.url}}" alt="image">
                        </figure>
                        <div class="team-meta__info">
                          <h6 class="team-meta__name">{{each.home_team}}</h6>
                        </div>
                      </div>
                    </td>
                    <td class="team-schedule__status">Away</td>
                    <td class="team-schedule__compet">{{each.season.competiton}}</td>
                    <td class="team-schedule__venue">{{each.match_location}}</td>
                  </tr>
                  {% endfor %}



                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div>
    {% endblock content %}